// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import * as ReactNative from "react-native";

function App$app(Props) {
  return React.createElement(ReactNative.SafeAreaView, {
              children: null
            }, React.createElement(ReactNative.StatusBar, {}), React.createElement(ReactNative.ScrollView, {
                  contentInsetAdjustmentBehavior: "automatic",
                  children: React.createElement(ReactNative.Text, {
                        children: "Baseball"
                      })
                }));
}

var app = App$app;

export {
  app ,
}
/* react Not a pure module */
